messages:
  welcome: "&aBonjour, %player%! Bienvenue sur ISEN-Craft."
  teleport: "&2Téléportation vers le spawn..."

settings:
  spawn-on-join: true
  navigation-cooldown-seconds: 3

welcome-title:
  title: "Bienvenue sur ISEN-Craft"
  subtitle: "&eRavi de vous revoir, &f%player% !"
  fade-in: 10
  stay: 40
  fade-out: 10
